# Definimos en que puerto correra
server:
  port: 7777

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mr_jeff_devenv
    username: postgres
    password: 1234



spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: alan.zarate@ucb.edu.bo
spring.mail.password: zoaixfxmzylunbnu
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
