# Definimos en que puerto correra
server:
  port: 7777

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mr_jeff
    username: postgres
    password: ABCabc123


