


CREATE OR REPLACE FUNCTION setHistoricPickUpUpdate()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS
$$
BEGIN
	IF NEW.MR_OPERATION_STATE_ID <> OLD.MR_OPERATION_STATE_ID THEN
			 INSERT INTO MR_PICKUP_HIST(MR_PICKUP_ID,MR_OPERATION_STATE_ID,MOMENT)
			 VALUES(OLD.MR_PICKUP_ID,NEW.MR_OPERATION_STATE_ID , now() );
	END IF;



	RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER triggerSetHistoricPickUpUpdate
AFTER UPDATE
ON MR_PICKUP
FOR EACH ROW
EXECUTE PROCEDURE setHistoricPickUpUpdate();


CREATE OR REPLACE FUNCTION setHistoricPickUpInsert()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS
$$
BEGIN

			 INSERT INTO MR_PICKUP_HIST(MR_PICKUP_ID,MR_OPERATION_STATE_ID,MOMENT)
			 VALUES(NEW.MR_PICKUP_ID,NEW.MR_OPERATION_STATE_ID , now() );



	RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER triggerSetHistoricPickUpInsert
AFTER INSERT
ON MR_PICKUP
FOR EACH ROW
EXECUTE PROCEDURE setHistoricPickUpInsert();